//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectNhom5
{
    using System;
    using System.Collections.Generic;
    
    public partial class HPHAN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HPHAN()
        {
            this.KQUAs = new HashSet<KQUA>();
        }
    
        public int MAHP { get; set; }
        public string MAMH { get; set; }
        public Nullable<int> HOCKI { get; set; }
        public Nullable<int> NAM { get; set; }
        public string GV { get; set; }
    
        public virtual MHOC MHOC { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KQUA> KQUAs { get; set; }
    }
}
