//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nhom5Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class DKIEN
    {
        public string MAMH { get; set; }
        public string MAMH_TRUOC { get; set; }
    
        public virtual MHOC MHOC { get; set; }
    }
}
