//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nhom5Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class MHOC
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MHOC()
        {
            this.DKIENs = new HashSet<DKIEN>();
            this.HPHANs = new HashSet<HPHAN>();
        }
    
        public string TENMH { get; set; }
        public string MAMH { get; set; }
        public Nullable<int> TINCHI { get; set; }
        public string MAKH { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DKIEN> DKIENs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HPHAN> HPHANs { get; set; }
        public virtual KHOA KHOA { get; set; }
    }
}
