//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nhom5Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class SVIEN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SVIEN()
        {
            this.KQUAs = new HashSet<KQUA>();
        }
    
        public string TEN { get; set; }
        public int MASV { get; set; }
        public Nullable<int> NAM { get; set; }
        public string MAKH { get; set; }
        public Nullable<System.DateTime> NAMSINH { get; set; }
        public Nullable<bool> GIOITINH { get; set; }
    
        public virtual KHOA KHOA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KQUA> KQUAs { get; set; }
    }
}
